### ISSUE TITLE
Add Configuration to Run Containers in MacOS (ARM)

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#187]
There are issues running the existing compose files in MacOS using their new ARM-based processors.

Documentation should be added, and new compose files should be added (if necessary) to make the application compatible with MacOS on ARM.

**Comment by yenaing-oo** [comment]
On Windows, when cloning the Secure-Record-Transfer repository, the `entrypoint.sh` script has executable file permission (-x) by default. This allows the app to run with no issues.
 
On Mac however, by default after cloning the repository, `entrypoint.sh` does not have executable file permission. After running `docker-compose up` with the necessary arguments, which should run the command (in the Containerfile) to add the executable file permission to `entryscript.sh` , its file permissions remain unchanged.

The current fix to this is to run:
`chmod +x docker/entrypoint.sh`
to manually add the executable file permission.

**Comment by danloveg** [comment]
It looks like it is possible to set the chmod through git: https://stackoverflow.com/a/38285462

So, one of the changes for this issue should involve making it so that pulling the code pulls this script as an executable.

**Comment by yenaing-oo** [comment]
> It looks like it is possible to set the chmod through git: https://stackoverflow.com/a/38285462
> 
> So, one of the changes for this issue should involve making it so that pulling the code pulls this script as an executable.

This method of setting file permissions to a file works. Running `chmod +x docker/entrypoint.sh` and pushing this change also works. Both methods were tested by:
1) pushing this change
2) deleting the local branch where the change was made
3) checking that the `master` branch's `entrypoint.sh` does not have the -x` file permission
4) checking out the branch where the change was made
5) seeing that the file permission on `entrypoint.sh` has the executable file permission

**Comment by yenaing-oo** [comment]
> There are issues running the existing compose files in MacOS using their new ARM-based processors.
> 
> Documentation should be added, and new compose files should be added (if necessary) to make the application compatible with MacOS on ARM.

It appears that running the containers with the existing `compose.*.yml` for both development and production using `podman-compose -f compose.*.yml up -d` works fine on MacOS, without having to specify any platform for any service.

**Comment by danloveg** [comment]
Oh well that's great that it's working. So is the only issue that the entrypoint script is not made executable when first pulling the code?

**Comment by yenaing-oo** [comment]
> Oh well that's great that it's working. So is the only issue that the entrypoint script is not made executable when first pulling the code?

Yes that's correct. As for the compose files being compatible when using Podman on MacOS ARM, could you verify this with me on our next meeting before closing this issue?

**Comment by danloveg** [comment]
Closed by #189 - thanks @yenaing-oo
