### ISSUE TITLE
Fix Body Height in Firefox Browser

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#188]
The body of the document does not take the full height of the window when there is a relatively small amount of content on the page and the window is taller than the combined height of the elements.

This should be addressable by adding `height: 100%;` to the body element.

![Screenshot 2024-07-24 133656](https://github.com/user-attachments/assets/e3993f0f-50a6-498e-bc52-5f938d3e01ef)

**Comment by yenaing-oo** [comment]
I can't seem to recreate this issue when viewing this page on the Firefox Browser (for Mac):
![image](https://github.com/user-attachments/assets/b60da413-0373-4fff-9714-2d4f3dec03ba)
 Perhaps this only affects Windows?

I also played around with changing the screen dimensions using Chrome's DevTools. The only issue I found was the main body text not being responsive for smaller screen sizes:

![image](https://github.com/user-attachments/assets/a288671f-f2f7-45bb-a305-e1860abb496f)

**Comment by danloveg** [comment]
Hmm, that's interesting. It's possible it only affects Windows.

Does adding `height: 100%` negatively affect how the pages render in your browser? That had fixed the issue on my machine.

**Comment by yenaing-oo** [comment]
I'll try testing this on my WIndows machine as well. 

Could you let me know in which file you added the `height: 100%;`?

**Comment by danloveg** [comment]
> Could you let me know in which file you added the `height: 100%;`?

[Try adding it here](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/master/bagitobjecttransfer/recordtransfer/static/recordtransfer/css/base/base.css#L10)

**Comment by yenaing-oo** [comment]
I tested the app in Firefox on Mac, and deleted some of the content on the About page, and discovered the mentioned issue:

![image](https://github.com/user-attachments/assets/e0e04ad3-a1e0-4bf5-a40a-e0492471233d)

Strangely, Chrome does not have this issue.

After adding `body { height: 100% }`, this fixed the issue:

![image](https://github.com/user-attachments/assets/b2555311-0267-4efa-bf07-05c38d4e431a)
