### ISSUE TITLE
Add Linting Configuration

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#191]
A linting configuration should be added to the application so that code style is enforced. These changes should be made:

- Add the NCTR's `ruff.toml` configuration to the root of the repo and test that it understands Django. One place to check will be the `models.py` file.
- Add a `DEVELOPERS.md` file, and add a note about setting up Ruff in VSCode.
- Add a link to the `DEVELOPERS.md` file from the README.

If it's desired later on, we can enforce linting with GitHub actions, but for now there'll be tons of linting issues and fixing them all at once is not recommended.

**Comment by yenaing-oo** [comment]
Would it be a good idea to use an automated process that ensures that the ruff.toml configuration used in every Python project is synced with the ruff.toml file in the Python Development Guide?

The simple but laborious way to check if any project's ruff.toml configuration is up to date is by manually copy-pasting the contents of `ruff.toml` from the Python Development Guide into your project every now and then, and then committing any changes (if `ruff.toml` is tracked).

I was thinking we could package and publish the Python Development Guide, and add it as a dependency in any Python project we work on. Any time the main branch is updated, a CI/CD pipeline will be triggered to publish the package again.

**Comment by danloveg** [comment]
That could work, but where would you suggest we publish that file? The Python Development Guide is basically a `ruff.toml` file and nothing else.

But say we publish it to pypi.org - once it's installed, we would have to tell Ruff where to find the .toml file, which may (or may not?) be different depending on versions of Python or operating system.

Something you could try and test is publishing a package with the TOML file to [Test PyPi](https://packaging.python.org/en/latest/guides/using-testpypi/), and then see where it's pulled in the repo when installed with Poetry.

I 100% agree that pulling the changes manually is tedious.

**Comment by yenaing-oo** [comment]
I made a [merge request](https://scm.ad.umanitoba.ca/nctr/nctr-external/python-development-guide/-/merge_requests/9) on our Python Development Guide with an implementation of this solution.

It is possible to include the `ruff.toml` file within a package and locate it after it's been installed.

**Comment by danloveg** [comment]
Addressed in #202.
