### ISSUE TITLE
Remove Need for .dev.env by Providing Defaults

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#207]
To run the development environment, it should not be necessary to run `cp .example.dev.env .dev.env`.

Defaults can be supplied for every "required" environment variable when running in development mode, which should make it simpler to run the app the first time or run the tests.

The following settings are "required" but can be given defaults:

- BAG_STORAGE_FOLDER (default: `/app/media/bags/`)
- UPLOAD_STORAGE_FOLDER (default: `/app/media/uploaded_files/`)
- ARCHIVIST_EMAIL (default: `archivist@localhost`)

**Comment by yenaing-oo** [comment]
What about for `DJANGO_SETTINGS_MODULE`? The value defined in `example.dev.env` is `bagitobjecttransfer.settings.docker_dev` whereas the default value used in `manage.py` is `bagitobjecttransfer.settings.test`

**Comment by danloveg** [comment]
Good point about the settings module. We should set the default in these two places:

- https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/c5537138c442735474f3325a0d484c913db1ae7b/compose.dev.yml#L55
- https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/c5537138c442735474f3325a0d484c913db1ae7b/compose.dev.yml#L79

**Comment by danloveg** [comment]
Since a user will likely not have an `/app/` directory on their machine when they're running locally, BAG_STORAGE_FOLDER and UPLOAD_STORAGE_FOLDER should instead be set to:

- `media/bags/`
- `media/uploaded_files/`

respectively. This will ensure that the root directory for each of these paths exist because they'll be set to paths within the current directory.

**Comment by yenaing-oo** [comment]
Once this issue is complete, an additional change would be to remove `example.dev.env` as it will no longer be necessary.

**Comment by danloveg** [comment]
Now that #265 is merged, can you try removing `.dev.env` and see if Docker or Django complain? If not, we can remove `example.dev.env`.

**Comment by yenaing-oo** [comment]
> Now that #265 is merged, can you try removing `.dev.env` and see if Docker or Django complain? If not, we can remove `example.dev.env`.


The app container runs fine, but the rq_worker container breaks. I'm not sure why though:

```
2024-12-11 16:04:13 >> Running database migrations.
2024-12-11 16:04:14 Operations to perform:
2024-12-11 16:04:14   Apply all migrations: admin, auth, caais, contenttypes, dbtemplates, django_rq, recordtransfer, sessions, sites
2024-12-11 16:04:14 Running migrations:
2024-12-11 16:04:14   No migrations to apply.
2024-12-11 16:04:14   Your models in app(s): 'recordtransfer' have changes that are not yet reflected in a migration, and so won't be applied.
2024-12-11 16:04:14   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
2024-12-11 16:04:14 >> Starting RQ worker(s)
2024-12-11 16:04:14 Attaching debugger to port 8010
2024-12-11 16:04:14 System check identified some issues:
2024-12-11 16:04:14 
2024-12-11 16:04:14 WARNINGS:
2024-12-11 16:04:14 ?: (staticfiles.W004) The directory '/app/dist' in the STATICFILES_DIRS setting does not exist.
2024-12-11 16:04:16 System check identified some issues:
2024-12-11 16:04:16 
2024-12-11 16:04:16 WARNINGS:
2024-12-11 16:04:16 ?: (staticfiles.W004) The directory '/app/dist' in the STATICFILES_DIRS setting does not exist.
2024-12-11 16:04:16 Error 111 connecting to 0.0.0.0:6379. Connection refused.
```

**Comment by danloveg** [comment]
Docker complains for me, I can't even get it to run:

```
env file C:\Users\lovegrod\Documents\NCTR_Code\public\Secure-Record-Transfer\.dev.env not found: CreateFile C:\Users\lovegrod\Documents\NCTR_Code\public\Secure-Record-Transfer\.dev.env: The system cannot find the file specified.
```

**Comment by danloveg** [comment]
Also, check this out: https://github.com/docker/compose/issues/3560#issuecomment-1933045798

**Comment by yenaing-oo** [comment]
> Also, check this out: [docker/compose#3560 (comment)](https://github.com/docker/compose/issues/3560#issuecomment-1933045798)

I actually completely removed this part from the compose file:
```
    env_file:
      - .dev.env
```

But setting required to false would also work. 

The rq_worker container still breaks though. I don't know what environment variable it needs to run, since the error logs don't mention anything aside from a connection failure to what I assume to be the Redis server.

**Comment by danloveg** [comment]
> > Also, check this out: [docker/compose#3560 (comment)](https://github.com/docker/compose/issues/3560#issuecomment-1933045798)
> 
> I actually completely removed this part from the compose file:
> 
> ```
>     env_file:
>       - .dev.env
> ```
> 
> But setting required to false would also work.
> 
> The rq_worker container still breaks though. I don't know what environment variable it needs to run, since the error logs don't mention anything aside from a connection failure to what I assume to be the Redis server.

I think I found the issue. The `DJANGO_SETTINGS_MODULE` is set to `test` by default. I don't know why I never thought of this, but the `DJANGO_SETTINGS_MODULE` can just be set here:

https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/7bf4f5856e75f34a6186b1dc4484323d69f1de7d/compose.dev.yml#L79

I'd say keep the `.dev.env` file but mark it as not required. If someone wants to test with different features enabled/disabled, they can make those changes in `.dev.env`, and that file will not be committed to the repo.

Something I can test is whether that `env_file` syntax is supported in Podman, it seems like it was added pretty recently to Docker.

**Comment by yenaing-oo** [comment]
I see, it wasn't using the right setting module in the rq_workers container.

I've applied your suggestions in this [pull request](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/pull/271).
