### ISSUE TITLE
Admin Static Files Fail to Load in Production

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#212]
All the places where a `Media` class is present in a model admin class cause a 500 Internal Server Error when the pipeline is enabled.

To reproduce the error for the Media class in `UploadedFileAdmin`, for example:

- Log in as an admin user
- Go to /admin/
- Click "Uploaded files" under the Record Transfer heading
- 500 error!

See [the documentation in django-pipeline here](https://django-pipeline.readthedocs.io/en/latest/usage.html#form-media) for how to fix this issue.

There are three instances of a Media class:

- `recordtransfer.admin.UploadedFileAdmin` (To see this page click "Uploaded files" in the admin site)
- `caais.admin.SourceOfMaterialInlineAdmin` (To see this page click "CAAIS metadata" in the admin site)
- `caais.admin.MetadataAdmin` (To see this page click "CAAIS metadata" in the admin site)

**Comment by yenaing-oo** [comment]
Currently, `hideMediaLink.js` is only being used by `recordtransfer.admin.UploadedFileAdmin`, but it is included in `/recordtransfer/static/recordtransfer/js/base`. Should `hideMediaLink.js` be moved elsewhere, perhaps a separate static directory for specifically the admin page?

Also, could you let me know why `caais` has its own directory in this project? From reading the docs, I understand that `caais`-specific models are defined in there, but I'm a bit confused as to why everything in `caais` isn't combined with `recordtransfer`.

**Comment by danloveg** [comment]
> Currently, `hideMediaLink.js` is only being used by `recordtransfer.admin.UploadedFileAdmin`, but it is included in `/recordtransfer/static/recordtransfer/js/base`. Should `hideMediaLink.js` be moved elsewhere, perhaps a separate static directory for specifically the admin page? I have the same question about `metadataChangeForm.css` which is only used in `caais.admin.MetadataAdmin`, which controls a part of the admin interface.
> 
> Also, could you let me know why `caais` has its own directory in this project? From reading the docs, I understand that `caais`-specific models are defined in there, but I'm a bit confused as to why everything in `caais` isn't combined with `recordtransfer`.

Feel free to move `hideMediaLink.js` somewhere else, I don't see a need for it to be included in `base/`.

`caais` has it's own directory because it's a different app within the bagitobjecttransfer project (see here for an explanation of project vs app: https://stackoverflow.com/a/19351042).

We talked in the past about publishing `caais` as a separate installable app other people could use in their own Django projects, so I decoupled it from the recordtransfer app.

**Comment by yenaing-oo** [comment]
> Feel free to move `hideMediaLink.js` somewhere else, I don't see a need for it to be included in `base/`.
> 
> `caais` has it's own directory because it's a different app within the bagitobjecttransfer project (see here for an explanation of project vs app: https://stackoverflow.com/a/19351042).
> 
> We talked in the past about publishing `caais` as a separate installable app other people could use in their own Django projects, so I decoupled it from the recordtransfer app.

I see this makes a lot of sense.
