### ISSUE TITLE
Split JS for multi-stage transfer form

### ISSUE THREAD

**Issue by yenaing-oo** [NationalCentreTruthReconciliation/Secure-Record-Transfer#235]
- Split the relevant JS for each form step into separate files and load them where needed
- Remove forms.js from static/recordtransfer/js/base

This way, only the relevant JS is loaded for each page, and it will no longer be necessary to avoid running portions of JS where constants are missing, since they are expected to be there.

For e.g. currently, we might have to do something like this in JS to prevent a console error on pages where this constant is not needed:
```
if (typeof ID_SUBMISSION_GROUP_SELECTION !== 'undefined') {
        const selectField = $('#' + ID_SUBMISSION_GROUP_SELECTION);
        selectField.on('change', updateGroupDescription);
        initializeGroupTransferForm();
    }
```
This means that if the constant `ID_SUBMISSION_GROUP_SELECTION` is not being passed to the JS in a situation where we **do** need it, it would be hard to detect since no error is raised.

**Comment by danloveg** [comment]
Would this require that a separate minified JS file be created per page of the form? Not saying that's a bad thing, just wondering.

**Comment by yenaing-oo** [comment]
Yes it would. I think if we plan on doing this, it might be a good idea to consider placing the contents of these `includes` within the templates themselves, instead of storing them in separate include templates:
```
{% if DEBUG %}
    {% load static %}
    <script src="{% static 'recordtransfer/js/profile/profile.js' %}"></script>
{% else %}
    {% load pipeline %}
    {% javascript 'recordtransfer_profile_js' %}
{% endif %}
```

**Comment by danloveg** [comment]
This may or may not be related, but I'm seeing this error on the Record Description part of the form when I try to open a date picker:

![Screenshot 2024-11-14 142345](https://github.com/user-attachments/assets/77a3e4f1-f724-486d-909d-8ee5a86b2bb5)

**Comment by danloveg** [comment]
Also JS related, when you click "More" on the rights form set or other identifiers form set, *three* more forms get added, but only one should be added.

**Comment by danloveg** [comment]
Related to #247. I could see there being multiple "entrypoints" in webpack, one for the overarching JS that the whole site needs, and one for each of the special case pages like the pages of the transfer form

**Comment by yenaing-oo** [comment]
Upon further consideration, having a separate JS file for each step of the form is not ideal in terms of efficiency in loading. It would be acceptable to have one JS file (say forms.js) for all the transfer form pages.

**Comment by yenaing-oo** [comment]
Resolved by https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/pull/248
As mention in last comment, there is no need to have separate JS for each step of the form, a single JS bundle for the entire multi-stage form suffices.
