### ISSUE TITLE
Minified static assets (JS and CSS) are being generated for development

### ISSUE THREAD

**Issue by yenaing-oo** [NationalCentreTruthReconciliation/Secure-Record-Transfer#245]
Minified CSS and JS should not be generated when running in development. This causes issues such as the same JS running 3 times:

![image](https://github.com/user-attachments/assets/f3d4881f-bc17-4922-bd65-dac05bbd04bc)

**Comment by yenaing-oo** [comment]
@danloveg 

I found that even though `DEBUG` is set to `True` in `docker_dev.py`, `DEBUG` itself never actually got passed  as context to templates:

![image](https://github.com/user-attachments/assets/0fe3843e-25dd-4bde-803f-a1e06824207c)

If you add the above without any other changes and open any page of the app on your browser, you will see that the `else` condition is fired and the value of `DEBUG` is empty.

It turns out that the `debug` context processor only passes the `debug` variable as context if the request made came from an IP that is listed in `settings.INTERNAL_IPS` (a setting that has not been set yet), in addition to `settings.DEBUG` being `True`:
![image](https://github.com/user-attachments/assets/d294dc94-6844-49c7-9348-9e24b23e08d4)
![image](https://github.com/user-attachments/assets/8502ab23-174c-4d81-9bc4-2ba99300de82)

I tried adding this setting to `docker_dev.py`:
```
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]
```

But this didn't work. Upon studying the value of `self.request.META["REMOTE_ADDR"]` a given request (say the About page), I discovered that the IP address is actually not `localhost` ('127.0.0.1'), but `192.168.65.1` instead.

It appears that Docker is intercepting any requests made by my local host and relaying it to the `app` service using its own default IP address `192.168.65.1`. 

I believe this IP address can be configured in Docker's settings here:
![image](https://github.com/user-attachments/assets/64000ec0-2bd0-4831-a421-0bf7ce433b4c)
, although the actual IP address on the request is slightly different (note the .1 at the end instead of .0).

Modifying this setting:
```
INTERNAL_IPS = [
     '192.168.65.1'
]
```

and replacing any `{% if DEBUG %}` with `{% if debug %}` fixes this issue.

**Comment by danloveg** [comment]
That makes sense. My question is, it seems like django-pipeline will send un-minified assets when DEBUG=True automatically - what happens when you try to use this without checking whether debug is true in the template?

```
{% load pipeline %}
{% javascript 'recordtransfer_base_js' %}
```

Or in other words, what error is thrown when you use that code when the pipeline is disabled?

**Comment by yenaing-oo** [comment]
Checking if debug is true:
![image](https://github.com/user-attachments/assets/fe6e2a33-266d-4e7b-a8ef-375a59bbd47a)
![image](https://github.com/user-attachments/assets/9b00a1bc-165b-4a87-8cdb-9c6a5c74a2b6)


Without checking if debug is true:
![image](https://github.com/user-attachments/assets/94a51adc-a664-4803-bd61-47d28c56b7d9)

![image](https://github.com/user-attachments/assets/43818078-8108-4c6f-b456-266b718d89d4)

**Comment by danloveg** [comment]
Okay, so when you don't check is how you get three versions of the same file.

My concern is about the IP address, I don't know whether we can assume everyone's Docker (or Podman) network will be set to `192.168.65.0/24`. I wonder if we can't just make a custom context processor that doesn't have that requirement.

Other context processors can be found here: https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/master/bagitobjecttransfer/recordtransfer/context_processors.py

**Comment by yenaing-oo** [comment]
Yes, that would work too! I'll make one.

**Comment by danloveg** [comment]
Sounds great, thanks

**Comment by danloveg** [comment]
Closing in favour of #247
