### ISSUE TITLE
Include jQuery/Dropzone using webpack

### ISSUE THREAD

**Issue by yenaing-oo** [NationalCentreTruthReconciliation/Secure-Record-Transfer#249]
Currently, CDNs are being used to load jQuery/Dropzone libraries. It would be preferrable to use npm to install these, as this allows for more convenient version control and the ability to minify these libraries, if that is standard practice.

**Comment by danloveg** [comment]
I played around with including Dropzone in `dropzoneForm.js` and it seemed to be as simple as:

```shell
npm install dropzone@5.9.3
```

And including this at the top of the file:

```javascript
// dropzoneForm.js
import { Dropzone } from 'dropzone';
```

This would be a good addition because then Dropzone is only loaded in `transferform.bundle.js`.

**Comment by yenaing-oo** [comment]
You're right, it looks like `webpack` includes all the code needed to use Dropzone on the client side during bundling. I just tested it out myself and it works perfectly in place of the CDN:
![image](https://github.com/user-attachments/assets/231b082c-7ba5-4fa3-acfa-1e3b6d171111)
I'm assuming that Webpack further minifies this imported source code in production, so we don't have to do anything extra.

**Comment by danloveg** [comment]
Don't worry about jQuery for this issue - I am aiming to have it removed in #256. So it's enough for this issue to only cover the Dropzone dependency.
