### ISSUE TITLE
Enable name field on profile form

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#251]
A user should be able to update their name on the profile page. The field is currently greyed out - the field should be enabled so that the user can change their name.

**Comment by yenaing-oo** [comment]
@danloveg 

When a user first signs up, they had to enter their first and last name:
![image](https://github.com/user-attachments/assets/1bdb21e5-e451-4d14-bce3-9c35a6437576)

Currently, the "Name" that is being displayed on the Profile page is a user's full name, constructed from their first and last name:

```html
    <div class="flex-item margin-top-25px">
        <label>{% trans "Name" %}</label>
        <input disabled value="{{ user.get_full_name }}">
    </div>
```


```python
class User(AbstractUser):
    """The main User object used to authenticate users"""

    gets_submission_email_updates = models.BooleanField(default=False)
    confirmed_email = models.BooleanField(default=False)
    gets_notification_emails = models.BooleanField(default=True)

    def get_full_name(self):
        return self.first_name + " " + self.last_name
```

Do we want to add fields in the profile page to modify the first and last name separately? This makes the most sense to me, but I just wanted to check with you.

**Comment by danloveg** [comment]
> Do we want to add fields in the profile page to modify the first and last name separately? This makes the most sense to me, but I just wanted to check with you.

Good point. Yes, that field should be split into two, one for the first name and one for the last name. Both should be required, since they're both required on the sign up form.
