### ISSUE TITLE
Minify images using webpack

### ISSUE THREAD

**Issue by yenaing-oo** [NationalCentreTruthReconciliation/Secure-Record-Transfer#252]
It appears that generating images in  the `.webp` format (as a form of minification) from the orignal images using  Webpack's [ImageMinimizedWebpackPlugin](https://webpack.js.org/plugins/image-minimizer-webpack-plugin/#generate-webp-images-from-copied-assets) does not work when in development mode. This is an issue as the images have to be referenced by their exact filename and extension in Django templates.

An alternative would be to try loading images dynamically from JS ([see example](https://webpack.js.org/plugins/image-minimizer-webpack-plugin/#query-parameters-only-squoosh-and-sharp-currently)] and modify the DOM to add these images, which webpack will optimize/minify during its build of static assets.

If that does not work, try other Webpack plugins, and as a last resort, try using a django library instead.

**Comment by danloveg** [comment]
This should be complete as #264 is merged in, right? @yenaing-oo

**Comment by yenaing-oo** [comment]
> This should be complete as #264 is merged in, right? @yenaing-oo

Yes that's correct. We are using `sharp` in favour of `webpack` plugins, so we can close this issue.
