### ISSUE TITLE
Allow Users to Turn off Emails From Profile Page

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#26]
A user should be able to manage their email notifications from the Profile page. A new field will likely need to be added to the `models.User` section to allow for this. The field on the user would also need to be checked when an email is sent.

**Comment by whikloj** [comment]
Also I noticed that the email templates already contain text to unsubscribe but without the link.
ie.
https://github.com/danloveg/NCTR-Bagit-Record-Transfer/blob/master/bagitobjecttransfer/recordtransfer/templates/recordtransfer/email/activate_account.html#L32

**Comment by whikloj** [comment]
I was going to do this one. Is this the use of the  [`gets_bag_email_updates`](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/b5afad4d4f8ec50a6511c643df2594a25ae062b5/bagitobjecttransfer/recordtransfer/models.py#L35) field already defined in the User model?
