### ISSUE TITLE
File Contents Should be Checked Before Upload

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#60]
The contents of every file should be verified with [ClamAV](https://www.clamav.net/) before being accepted.

Required changes:
- Link in [docker-clamav](https://hub.docker.com/r/mkodockx/docker-clamav/) to the docker-compose file so that the files can be checked when running in Docker mode
- Implement `recordtransfer.views._accept_contents` with [clamd](https://pypi.org/project/clamd/)
- Update documentation to include ClamAV setup on production server
- Send an email to administrators for every file that is found to contain malicious content

**Comment by whikloj** [comment]
We have interest in getting the scanning integrated, so I'll take a crack at this.

**Comment by danloveg** [comment]
Sound good. I already "kind of" implemented the logic in `recordtransfer.views._accept_contents`. I also would like to see a [docker-clamav](https://hub.docker.com/r/mkodockx/docker-clamav/) container being added to the `docker-compose.yml` file

**Comment by danloveg** [comment]
> Sound good. I already "kind of" implemented the logic in `recordtransfer.views._accept_contents`. I also would like to see a [docker-clamav](https://hub.docker.com/r/mkodockx/docker-clamav/) container being added to the `docker-compose.yml` file

I didn't even look at the issue, I already wrote all this when I created the issue!

**Comment by whikloj** [comment]
Sorry are we allowing clamav to be installed locally (ie. unix sockets) or remotely (ie. tcp sockets) or both?

**Comment by whikloj** [comment]
Sorry I saw the link to the clamd and thought it was actual clamd. Trying that module now.
