### ISSUE TITLE
Allow users to save/resume a transfer

### ISSUE THREAD

**Issue by whikloj** [NationalCentreTruthReconciliation/Secure-Record-Transfer#76]
As the title says, allow users to save a transfer before completing it and come back to it later without having to re-enter any data.

Suggested starting points
> The transfer form is using a [SessionWizardView](https://django-formtools.readthedocs.io/en/latest/wizard.html#formtools.wizard.views.SessionWizardView), which persists the data to the database using a database session. The documentation for Django sessions is [here](https://docs.djangoproject.com/en/3.2/topics/http/sessions/#module-django.contrib.sessions).

**Comment by danloveg** [comment]
Closed by #83. Some work may need to be done in the future to save the current form data when the form is saved. Open a separate issue if this comes up.
